# Generated by Django 3.1.1 on 2020-10-08 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppPerris', '0002_auto_20201008_1736'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AnimalRescatado',
            new_name='Rescatado',
        ),
    ]
