# Generated by Django 3.1.1 on 2020-10-08 21:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppPerris', '0003_auto_20201008_1749'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SolicitudAdopcion',
        ),
    ]
